import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Marquee from "./components/Marquee";
import { ToastContainer } from "react-toastify";

const notoSerifBengali = Noto_Serif_Bengali({
 
  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <Marquee></Marquee>
        <main className="mx-auto w-full max-w-7xl flex-1 px-4">
          {children}
        </main>
        <ToastContainer />
        </body>
    </html>
  );
}
